version: '3'
services:

  mailhog:
    image: mailhog/mailhog
    networks:
      - test_network

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=poc_features
    networks:
      - test_network

  redis:
    image: redis
    networks:
      - test_network

  app:
    image: registry.heroku.com/peaceful-refuge-95132/web
    environment:
      # NOTICE: uncomment this if you need to display logs for debugging
      #- RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=features
      - MAILHOG_HOST=mailhog
      - RAILS_MASTER_KEY
      - "GITHUB_CLIENT_ID=${FEATURES_GITHUB_CLIENT_ID}"
      - "GITHUB_SECRET=${FEATURES_GITHUB_SECRET}"
      - GITHUB_CALLBACK_DOMAIN=http://bootcamp.app.com:3000
      - DATABASE_HOST=postgres
      - REDIS_URL=redis://redis:6379
      - RECAPTCHA_SITE_KEY
      - RECAPTCHA_SECRET_KEY
    depends_on:
      - postgres
      - redis
      - mailhog
    networks:
      test_network:
        aliases:
          - app.com
          - www.app.com
          - bootcamp.app.com
          - dashboard.app.com
          - idea.app.com
    command: >
      /bin/bash -c "
        while ! nc -z postgres 5432;
        do
          echo Waiting for PG;
          sleep 1;
        done;
        rake db:schema:load;
        rm -f /app/tmp/pids/server.pid;
        foreman start;
      "

  features:
    image: howtohireme/give-me-poc-features:${CURRENT_TAG}
    container_name: features_1
    depends_on:
        - app
    environment:
      - CUCUMBER_HOST=http://www.app.com:3000
      - POSTGRES_HOST=postgres
      - GITHUB_TEST_EMAIL
      - GITHUB_TEST_PASSWORD
      - GITHUB_NON_PUBLIC_EMAIL
      - GITHUB_NON_PUBLIC_PASSWORD
    networks:
      - test_network
    volumes:
      - ./artifacts:/app/artifacts
    command: >
      /bin/bash -c "
        while ! nc -z www.app.com 3000;
        do
          echo Waiting for app;
          sleep 1;
        done;
        cucumber;
      "

networks:
  test_network:
    driver: bridge
